Program
    = { Statement }, EOI
    ;

Statement
    = ( Assignment | ExitStmt ), Semicolon
    ;

ExitStmt
    = Exit, Expression
    ;

Assignment
    = Identifier, ColonEqual, Expression
    ;

Expression
    = Power
    ;

Power
    = Term, Pow, Term
    ;

Term
    = Factor, { (Minus | Plus), Factor }
    ;

Factor
    = Unary, { (Div | Mul | Mod), Unary }
    ;

Unary
    = Minus, Unary
    | Primary
    ;

Primary
    = IntLiteral
    | Identifier
    | LeftParen, Expression, RightParen
    ;
