Program
    = { Statement }, EOI
    ;

Statement
    = ( Assignment | ExitStmt ), Endl
    ;

ExitStmt
    = Exit, Expression
    ;

Assignment
    = Identifier, ColonEqual, Expression
    ;

Expression
    = BinExpression
    | UnExpression
    | Factor
    ;

BinExpression
    = Factor, Pow, Factor
    | Factor, ( Mul | Div | Mod ), Factor
    | Factor, ( Plus | Minus ), Factor
    ;

UnExpression
    = Minus, Factor
    ;


Factor
    = Identifier
    | IntLiteral
    | LeftParen, Expression, RightParen
    ;