#!/usr/bin/env python3
import rich_click as click
import rich

console = rich.console.Console()


@click.command()
@click.option(
    "-i", "--input", default="main.drgns", type=str, help="Path to input file"
)
@click.option(
    "-c",
    "--check",
    is_flag=True,
    default=False,
    help="Lint the file without running it",
)
def main(**kwargs):
    pass


if __name__ == "__main__":
    main()
